apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: ClusterIP
  ports:
    - port: 8888        # Port exposed by the service
      targetPort: 88888 # Port on the container inside the pod
      protocol: TCP
  selector:
    app: wil-playground
